repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.1
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        exclude: api-spec.d.ts
        additional_dependencies:
          - eslint@^8.27.0
          - eslint-config-airbnb-base@^15.0.0
          - eslint-plugin-import@^2.26.0
          - eslint-plugin-vue@^9.7.0
          - vue-eslint-parser
          - eslint-plugin-prettier
          - eslint-config-prettier
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - "@nuxtjs/eslint-config-typescript"
          - "@nuxt/eslint-config"
          - eslint-import-resolver-typescript
          - eslint-plugin-unicorn
          - eslint-plugin-n
          - eslint-plugin-promise
        args: [--fix --ignore-pattern services/playground/]
